apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - image: 084898106549.dkr.ecr.us-east-1.amazonaws.com/payments:latest
          name: payments
          env:
            - name: PORT
              value: '3001'
            - name: NOTIFICATIONS_HOST
              value: notifications
            - name: NOTIFICATIONS_PORT
              value: '3000'
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: apiKey
          ports:
            - containerPort: 3001
